# ---------------------------------------------------------------------------#
seed:                     # TODO: random seed for reproducibility

# xtb parameters
gfn: '2'
etemp:
solvent:
chrg:
uhf: '0.0'

# Potential "wall" keeping molecules together. The following are just the
# lines of the wall group. This is needed mainly for the metadynamics portion,
# otherwise the molecules just fly away from eachother.
wall:
  - 'potential=logfermi'
  - 'sphere: auto, all'

# ---------------------------------------------------------------------------#
# Parameters related to the coordinate driving

# Atoms of driven coordinate. The number of atoms given defines the driving
# type:
# - 2 atoms -> distance driving
# - 3 atoms -> bend driving
# - 4 atoms -> torsional driving
atoms:

# Lower and upper limits applied to the driven coordinate. If a single number
# is given, the lower limit defaults to the value of the coordinate in the
# equilibrium geometry. driving_num sets the number of discretized values the
# driven coordinate takes.
driving_limits:
driving_num: 50

# Force of coordinate driving, in Hartree/bohr or Hartree/angle (?
# TODO:CHECK). If empty and a distance driving is applied, the force is
# determined the bond strength computed at starting geometry. For angles, the
# default value is 1.0.
force:

# Optimization level used during coordinate driving relaxed scans.
optim: normal

# ---------------------------------------------------------------------------#
# Metadynamics initial conformer seeding

# To get a good coverage of conformers, we initially perform (if imtd = true)
# a metadynamics run to generate a set of starting structures at the initial
# value of the driven coordinate.
imtd: true

# Time per atom of the initial mtd run.
imtd_time_per_atom: 0.5

# Metadynamics potential parameters (adapted from CREST mquick) for the
# $metadyn block in xtb.
imtd_metadyn: ["kpush=0.200", "alp=0.200"]

# MD parameters for the $md block in xtb. The initial metadynamics is
# performed with shake=2, a 5fs step and structures dumped every 100 fs.
imtd_md: ["shake=2","step=5","dump=100"]

# ---------------------------------------------------------------------------#
# Metadynamics transition structure search

# The following parameters set the points along the driven coordinate at which
# metadynamics searches are performed. By default, that is at every point
# (mtd_step=1) over the first half of the values of the driven coordinate
# (mtd_lims = [0.0, 0.5]).
mtd_step: 1
mtd_lims: [0.0, 0.5]            # Start and end values of the driven
                                # coordinate where driving is performed, as
                                # fractions of total coordinate range.

# Alternatively, the indices at which the coordinate driving is performed can
# be set explicitly.
mtd_indices:

# The following parameters relate to the metadynamics propagations themselves.
# The defaults balance performance and exploration.

# Time per atom of metadynamics propagation, in ps.
tsmtd_time_per_atom: 0.1

# The remaining parameters are adapted from the CREST paper. We do four sample
# at each index, with variying kpush and alpha parameters (similar to CREST
# -mquick).
tsmtd_params:
  - ["save=30", "kpush=0.200", "alp=0.800"]
  - ["save=30", "kpush=0.200", "alp=0.200"]
  - ["save=30", "kpush=0.050", "alp=0.800"]
  - ["save=30", "kpush=0.050", "alp=0.200"]

# For the TS search, we turn SHAKE off
tsmtd_md: ["shake=0","step=2","dump=100"]

# ---------------------------------------------------------------------------#
# Reaction search parameters
# These parameters are related to the selection of metadynamics-derived
# transition structures for further coordinate driving. For this, we use the
# CREGEN routine from CREST. However, the parameters are significantly less
# strict than the CREST ones because we want to really push diversity and
# limit similarity.
ewin: 60.0                      # maximum energy in kcal /mol above the energy
                                # of the initial structure E0.
rthr: 0.4                       # RMSD threshold (in A)
ethr: 1.0                       # energy threshold (in kcal/mol)
bthr: 2.0                       # rotational const threshold

# Before we start CREGEN, we first optimize the structures obtained in
# metadynamics at the following optimization level.
optcregen: tight


# ---------------------------------------------------------------------------#
# Finally, the initial molecular structure is given here.
xyz: |
  3

  O    0.00   0.00  0.00
  etc.
