# ---------------------------------------------------------------------------#
# Parameters passed to xtb
etemp: '300.0'                 # electronic temperature
gfn: '2'                       # gfn version
solvent:
chrg:
uhf:

# ---------------------------------------------------------------------------#
# Optimization of stretched and unstretched structures. 
optim: tight                  # default level
wall: 
  # Potential "wall" keeping molecules together. The following are just the
  # lines of the wall group.
  - 'potential=logfermi'
  - 'sphere: auto, all'

# ---------------------------------------------------------------------------#
# Parameters used by CREGEN to compare structures and decide if they are
# identical. These are more generous (significantly) than the CREST one
# because we want to really push diversity and limit similarity.
optcregen: lax
ewin: 70.0                      # maximum energy in kcal /mol above the energy
                                # of the initial structure E0.
rthr: 0.4                       # RMSD threshold (in A)
ethr: 0.5                       # energy threshold (in kcal/mol)
bthr: 2.0                       # rotational const threshold

# ---------------------------------------------------------------------------#
# Parameters related to the atoms to be stretched. This will then be
# turned into constraints.
atoms:
stretch_limits: [1.0, 3.0]
force: 1.0                      # in Hartree/bohr
# One of these two should be set
stretch_num: 100                # Number of points for stretch
stretch_resolution:             # Resolution of stretch in A



# ---------------------------------------------------------------------------#
# Points where metadynamics are performed.
mtd_only_reactant: false        # Do metadynamics only for the reactant.
mtd_step: 8                     # Metadynamics every x points of stretch. If
                                # false, do mtd only at TS and minima.

  
# ---------------------------------------------------------------------------#
metadynamics:
  nmtd: 120
  time_per_atom: 0.5            # total time / Natoms (ps) for each mtd run

  jobs:
    # These are the parameters for each metadynamics runs, taken from CREST
    # paper (nanoreactor part).
    - ["kpush=0.200", "alp=0.800"]
  md:
    - "shake=0"
    - "step=1"

# Initial geometry, as an xyz string
xyz: |
  3

  O    0.00   0.00  0.00
  etc.

