# ---------------------------------------------------------------------------#
# Parameters passed to xtb
gfn: '2'                       # gfn version
# Not setting the following = taking the xtb default
etemp:
solvent:
chrg:
uhf: '0'

# ---------------------------------------------------------------------------#
# Optimization of stretched and unstretched structures.
optim: normal

# Potential "wall" keeping molecules together. The following are just the
# lines of the wall group. This is needed mainly for the metadynamics portion,
# otherwise the molecules just fly away from eachother.
wall:
  - 'potential=logfermi'
  - 'sphere: auto, all'

# ---------------------------------------------------------------------------#
# Parameters used by CREGEN to compare structures and decide if they are
# identical. These are more generous (significantly) than the CREST one
# because we want to really push diversity and limit similarity.
ewin: 60.0                      # maximum energy in kcal /mol above the energy
                                # of the initial structure E0.
rthr: 0.4                       # RMSD threshold (in A)
ethr: 1.0                       # energy threshold (in kcal/mol)
bthr: 2.0                       # rotational const threshold

# Before we start CREGEN, we first optimize the structures obtained in
# metadynamics at the following optimization level,
optcregen: tight

# ---------------------------------------------------------------------------#
# Parameters related to the coordinate driving. This will then be
# turned into constraints.

# If there are:
# 2 atoms -> distance constraint
# 3 atoms -> angle constraint
# 4 atoms -> dihedral constraint
atoms:
const_limits:
const_num: 100
force:                          # Force of driving, in Hartree/bohr. If empty,
                                # the force is determined from four single
                                # point calculations at the starting geometry.



# ---------------------------------------------------------------------------#
# The following parameters determine where (in terms of bond stretch)
# metadynamics is performed.
mtd_only_reactant: true         # Do metadynamics only for the reactant.
mtd_step: 1                     # Metadynamics every x points of stretch. If
                                # null, do mtd only at TS and minima.
# We can also set those points explicitly.
mtdi:

# ---------------------------------------------------------------------------#
# The following parameters relate to the metadynamics portion. The defaults
# balance performance and exploration.
# This is the number of structure to harvest from each metadynamics job
time_per_atom: 0.1            # total time / Natoms (ps) for each job

# The remaining parameters are adapted from the CREST paper (the nanoreactor
# part). We do four sample at each index, with variying kpush and alpha
# parameters (similar to CREST conformer search).
mtdsave: 30
mtdjobs:
  - ["kpush=0.200", "alp=0.800"]
  - ["kpush=0.200", "alp=0.200"]
  - ["kpush=0.050", "alp=0.800"]
  - ["kpush=0.050", "alp=0.200"]
mtdmd:
  - "shake=0"                 # shake off
  - "step=2"                  # MD timestep, in fs
  - "dump=100"                # snapshot time (fs)

# Finally, the initial structure
xyz: |
  3

  O    0.00   0.00  0.00
  etc.
